### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BrianPugh** [G6EJD/ESP32-ADC-Accuracy-Improvement-function#4]
Hi G6EJD,

I was wondering if you could loosen the License requirement of this repo to MIT? I would like to use your found polynomial in another MIT project. Thanks!

Sincerely,
Brian

**Comment by G6EJD** [comment]
Well if you read the licence, providing the usage is for educational or private purposes you can use it, however if for commercial gain then no use is allowed.

**Comment by BrianPugh** [comment]
ok thank you.
