### ISSUE TITLE
Incorrect return values

### ISSUE THREAD

**Issue by bcodermicro** [G6EJD/ESP32-ADC-Accuracy-Improvement-function#5]
I just plugged 2900 into your formula and got 2.7V in return...any suggestiion?

-R

**Comment by G6EJD** [comment]
What were your test conditions?
The formula will only evaluate correctly if using a 32-bit cpu like ESP8266 and the double type that uses 8-bytes to represent a floating point number.
Please provide a code example and what cpu and compiler your using.
Trying to replicate the formula in Excel? See the Microsoft note: https://support.microsoft.com/en-us/help/78113/floating-point-arithmetic-may-give-inaccurate-results-in-excel

**Comment by bcodermicro** [comment]
Hey there.. i was having a senior moment. 
Had to *5 to the value so that it returns the batteery V within 1%.. 
Thanks.

**Comment by G6EJD** [comment]
Ok
