### ISSUE TITLE
Serial.print adc_chars.vref returns 0

### ISSUE THREAD

**Issue by techtoys** [G6EJD/ESP32-ADC-Accuracy-Improvement-function#8]
Hi

I am trying out your code of ESP32_ADC_VREF.ino with a serial printout for adc_chars.vref:

```
float ReadVoltage(byte ADC_Pin) {
  float calibration  = 1.000; // Adjust for ultimate accuracy when input is measured using an accurate DVM, if reading too high then use e.g. 0.99, too low use 1.01
  float vref = 1100;
  esp_adc_cal_characteristics_t adc_chars;
  esp_adc_cal_characterize(ADC_UNIT_1, ADC_ATTEN_DB_11, ADC_WIDTH_BIT_12, 1100, &adc_chars);
  vref = adc_chars.vref; // Obtain the device ADC reference voltage
  Serial.print(F("vref is : ")); Serial.println(vref);
  return (analogRead(ADC_Pin) / 4095.0) * 3.3 * (1100 / vref) * calibration;  // ESP by design reference voltage in mV
}
```

I expected vref would be value around 1100 but it turns out that it is always 0.

Did I miss something?

Besides, I also included a new line in setup() to see if calibration mode is supported in eFuse. I am using an ESP32S3. Code snippet shown below:

```
void setup() {
  Serial.begin(115200);
  delay(500);
  esp_err_t err;
  err = esp_adc_cal_check_efuse(ESP_ADC_CAL_VAL_EFUSE_VREF);
  switch(err){
    case ESP_OK:
    Serial.println(F("The calibration mode is supported in eFuse"));
    break;
    case ESP_ERR_NOT_SUPPORTED:
    Serial.println(F("Error, eFuse values are not burned"));
    break;
    case ESP_ERR_INVALID_ARG:
    Serial.println(F("Error, invalid argument (ESP_ADC_CAL_VAL_DEFAULT_VREF)"));
    break;
  }
}
```

From Serial Monitor I have got **Error, eFuse values are not burned**.

It may be the reason why vref is always 0. But how to fix that?

John

**Comment by G6EJD** [comment]
You can’t fix this, Espresiff have chosen not to implement the capability on the S3

**Comment by techtoys** [comment]
Yes, I found S3 only supports ESP_ADC_CAL_VAL_EFUSE_TP_FIT. With this efuse parameter esp_adc_cal_get_voltage() seems to work. The thread and complete sketch is available at https://esp32.com/viewtopic.php?f=19&t=34706&p=117149#p117149
